# Generated by Django 2.2.7 on 2019-11-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('nickname', models.CharField(blank=True, max_length=512, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PoliticalBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('type_of_body', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Political bodies',
            },
        ),
        migrations.CreateModel(
            name='PoliticalActionCommittee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=4096)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='political_action_committees', to='elections.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('office_holders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices_held', to='elections.Person')),
                ('political_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.PoliticalBody')),
            ],
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_order', models.IntegerField(default=0)),
                ('incumbent', models.BooleanField()),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='elections.Person')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.Office')),
            ],
            options={
                'verbose_name_plural': 'Candidacies',
            },
        ),
    ]
