# Generated by Django 2.2.7 on 2019-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='candidate_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
