# Generated by Django 2.2.7 on 2019-12-02 01:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoraid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='__str__'),
        ),
        migrations.AddField(
            model_name='office',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='__str__'),
        ),
        migrations.AddField(
            model_name='politicalbody',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='__str__'),
        ),
    ]
