# Generated by Django 2.2.7 on 2019-12-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoraid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='politicalbody',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
