# Generated by Django 3.0 on 2019-12-04 02:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoraid', '0003_auto_20191202_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='openstates_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=[], size=None),
            preserve_default=False,
        ),
    ]
