# Generated by Django 3.0 on 2019-12-04 02:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoraid', '0004_person_openstates_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isboe_committees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='openstates_id',
            field=models.CharField(max_length=64),
        ),
    ]
