# Generated by Django 3.0 on 2019-12-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoraid', '0005_auto_20191204_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='openstates_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
